# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a lightweight OpenJDK image
FROM openjdk:17-jdk-slim AS build

# Install JBang
RUN apt-get update && \
    apt-get install -y curl && \
    curl -Ls https://sh.jbang.dev | bash

# Set the working directory
WORKDIR /app

# Copy the JAR file for the filesystem server
ADD https://github.com/quarkiverse/quarkus-mcp-servers/releases/download/early-access/mcp-server-filesystem.jar /app/mcp-server-filesystem.jar

# Default entrypoint to run the MCP server using JBang
ENTRYPOINT ["jbang", "/app/mcp-server-filesystem.jar"]

# Command to be overridden at runtime to specify paths
CMD ["/path/to/folder1", "/path/to/folder2"]